version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8426
      POSTGRES_DB: user_information
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: chatuser
      DB_PASS: chatpass
      DB_NAME: chatdb
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data: